version: '3.5'
services:
  fourleft-web:
    build: ./nginx
    container_name: fourleft-proxy
    restart: always
    depends_on:
      - fourleft
    environment:
      - VIRTUAL_HOST=fourleft.busata.io
      - LETSENCRYPT_HOST=fourleft.busata.io
  fourleft:
    build: .
    container_name: fourleft
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=${DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASS}
      - CODEMASTERS_EMAIL=${CODEMASTERS_EMAIL}
      - CODEMASTERS_PASS=${CODEMASTERS_PASS}
    ports:
      - "8081:8081"
    depends_on:
      - db.fourleft
  db.fourleft:
    container_name: db.fourleft
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  pgdata:
networks:
  default:
    name: veevi