package io.busata.fourleft.club.championship.creator;

import io.busata.fourleft.club.championship.creator.StageOption;

import java.util.List;

import static io.busata.fourleft.club.championship.creator.StageOption.*;
import static io.busata.fourleft.club.championship.creator.StageOption.LAS_JUNTAS;

public enum StageConfiguration {

    ARGENTINA_A_FWD(LAS_JUNTAS, CAMINO_DE_ACANTILADOS_Y_ROCAS, LA_MERCED),
    ARGENTINA_A_REV(CAMINO_A_LA_PUERTA, EL_RODEO, CAMINO_DE_ACANTILADOS_Y_ROCAS_INVERSO),
    ARGENTINA_B_FWD(VALLE_DE_LOS_PUENTES,MIRAFLORES,CAMINO_A_CONETA),
    ARGENTINA_B_REV(VALLE_DE_LOS_PUENTES_A_LA_INVERSA,SAN_ISIDRO,HUILLAPRIMA),

    AUSTRALIA_A_FWD(MOUNT_KAYE_PASS,ROCKTON_PLAINS,YAMBULLA_MOUNTAIN_ASCENT),
    AUSTRALIA_A_REV(MOUNT_KAYE_PASS_REVERSE, YAMBULLA_MOUNTAIN_DESCENT, ROCKTON_PLAINS_REVERSE),
    AUSTRALIA_B_FWD(CHANDLERS_CREEK, NOORINBEE_RIDGE_ASCENT, BONDI_FOREST),
    AUSTRALIA_B_REV(CHANDLERS_CREEK_REVERSE, TAYLOR_FARM_SPRINT, NOORINBEE_RIDGE_DESCENT),

    FINLAND_A_FWD(KONTINJARVI, KAILAJARVI, NAARAJARVI),
    FINLAND_A_REV(HAMELAHTI, JYRKYSJARVI, PASKURI),
    FINLAND_B_FWD(KAKARISTO, ISO_OKSJARVI, KOTAJARVI),
    FINLAND_B_REV(PITKAJARVI,JARVENKYLA,OKSALA),

    GERMANY_A_FWD(OBERSTEIN, WALDAUFSTIEG, KREUZUNGSRING),
    GERMANY_A_REV(FRAUENBERG, KREUZUNGSRING_REVERSE, WALDABSTIEG),
    GERMANY_B_FWD(HAMMERSTEIN, VERBUNDSRING, INNERER_FELD_SPRINT_UMGEKEHRT),
    GERMANY_B_REV(RUSCHBERG, INNERER_FELD_SPRINT, VERBUNDSRING_REVERSE),

    GREECE_A_FWD(ANODOU_FARMAKAS, POMONA_EKRIXI, KORYFI_DAFNI),
    GREECE_A_REV(KATHODO_LEONTIOU, FOURKETA_KOURVA, AMPELONAS_ORMI),
    GREECE_B_FWD(PERASMA_PLATANI, OUREA_SPEVSI, ABIES_KOILADA),
    GREECE_B_REV(TSIRISTRA_THEA, PEDINES_EPIDAXI, YPSONA_TOU_DASOS),

    MONTE_CARLO_A_FWD(PRA_DALART, GORDOLON_COURTE_MONTEE, COL_DE_TURINI_SPRINT_EN_MONTEE),
    MONTE_CARLO_A_REV(COL_DE_TURINI_DEPART, COL_DE_TURINI_SPRINT_EN_DESCENTE, COL_DE_TURINI_DESCENTE),
    MONTE_CARLO_B_FWD(VALLEE_DESCENDANTE, COL_DE_TURINI_DEPART_EN_DESCENTE, ROUTE_DE_TURINI_DESCENTE),
    MONTE_CARLO_B_REV(ROUTE_DE_TURINI, APPROCHE_DU_COL_DE_TURINI_MONTEE, ROUTE_DE_TURINI_MONTEE),

    POLAND_A_FWD(ZAROBKA, KOPINA, BORYSIK),
    POLAND_A_REV(ZAGORZE, MARYNKA, JOZEFIN),
    POLAND_B_FWD(JEZIORO_ROTCZE, CZARNY_LAS, JAGODNO),
    POLAND_B_REV(ZIENKI, LEJNO, JEZIORO_LUKIE),

    SCOTLAND_A_FWD(SOUTH_MORNINGSIDE, OLD_BUTTERSTONE_MUIR, ROSEBANK_FARM_REVERSE),
    SCOTLAND_A_REV(SOUTH_MORNINGSIDE_REVERSE, ROSEBANK_FARM, OLD_BUTTERSTONE_MUIR_REVERSE),
    SCOTLAND_B_FWD(NEWHOUSE_BRIDGE, GLENCASTLE_FARM, ANNBANK_STATION_REVERSE),
    SCOTLAND_B_REV(NEWHOUSE_BRIDGE_REVERSE, ANNBANK_STATION, GLENCASTLE_FARM_REVERSE),

    SPAIN_A_FWD(COMIENZO_DE_BELLRIU, ASCENSO_POR_VALLE_EL_GUALET, ASCENSO_BOSQUE_MONTVERD),
    SPAIN_A_REV(FINAL_DE_BELLRIU, VINEDOS_DENTRO_DEL_VALLE_PARRA, SALIDA_DESDE_MONTVERD),
    SPAIN_B_FWD(CENTENERA, DESCENSO_POR_CARRETERA, VINEDOS_DARDENYA_INVERSA),
    SPAIN_B_REV(CAMINO_A_CENTENERA, VINEDOS_DARDENYA, SUBIDA_POR_CARRETERA),

    SWEDEN_A_FWD(RANSBYSATER, ALGSJON_SPRINT, STOR_JANGEN_SPRINT),
    SWEDEN_A_REV(NORRASKOGA, STOR_JANGEN_SPRINT_REVERSE, SKOGSRALLYT),
    SWEDEN_B_FWD(HAMRA, ELGSJON, OSTRA_HINNSJON),
    SWEDEN_B_REV(LYSVIK, BJORKLANGEN, ALGSJON),

    USA_A_FWD(NORTH_FORK_PASS, HANCOCK_CREEK_BURST, FULLER_MOUNTAIN_ASCENT),
    USA_A_REV(NORTH_FORK_PASS_REVERSE, FULLER_MOUNTAIN_DESCENT, FURY_LAKE_DEPART),
    USA_B_FWD(BEAVER_CREEK_TRAIL_FORWARD, HANCOCK_HILL_SPRINT_FORWARD, TOLT_VALLEY_SPRINT_FORWARD),
    USA_B_REV(BEAVER_CREEK_TRAIL_REVERSE, TOLT_VALLEY_SPRINT_REVERSE, HANCOCK_HILL_SPRINT_REVERSE),

    NEW_ZEALAND_A_FWD(TE_AWANGA_FORWARD, TE_AWANGA_SPRINT_FORWARD, OCEAN_BEACH_SPRINT_REVERSE),
    NEW_ZEALAND_A_REV(OCEAN_BEACH, OCEAN_BEACH_SPRINT_FORWARD, TE_AWANGA_SPRINT_REVERSE),
    NEW_ZEALAND_B_FWD(WAIMARAMA_POINT_REVERSE, WAIMARAMA_SPRINT_FORWARD, ELSTHORPE_SPRINT_REVERSE),
    NEW_ZEALAND_B_REV(WAIMARAMA_POINT_FORWARD, ELSTHORPE_SPRINT_FORWARD, WAIMARAMA_SPRINT_REVERSE),

    WALES_A_FWD(RIVER_SEVERN_VALLEY, FFERM_WYNT, DYFFRYN_AFON),
    WALES_A_REV(BRONFELEN, DYFFRYN_AFON_REVERSE, FFERM_WYNT_REVERSE),
    WALES_B_FWD(SWEET_LAMB, PANT_MAWR, BIDNO_MOORLAND),
    WALES_B_REV(GEUFRON_FOREST, BIDNO_MOORLAND_REVERSE, PANT_MAWR_REVERSE),
    ;

    private final StageOption longStage;
    private final StageOption firstShortStage;
    private final StageOption secondShortStage;

    StageConfiguration(StageOption longStage, StageOption firstShortStage, StageOption secondShortStage) {
        this.longStage = longStage;
        this.firstShortStage = firstShortStage;
        this.secondShortStage = secondShortStage;

    }


    public StageOption longStage() {
        return longStage;
    }

    public StageOption firstShort() {
        return firstShortStage;
    }

    public StageOption secondShort() {
        return this.secondShortStage;
    }

    public boolean containsOption(StageOption option) {
       return this.longStage == option || this.firstShort() == option || this.secondShort() == option;
    }

    public List<StageOption> getStages() {
        return List.of(longStage(), firstShort(), secondShort());
    }
}
